<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;</TargetFrameworks>
    <RootNamespace>InfoReg</RootNamespace>
    <AssemblyName>SI_Format</AssemblyName>
    <Authors>Information Register Limited</Authors>
    <Company>Information Register Limited</Company>
    <Description>SI_Format allows strings like 21.34km be parsed to return a numerical value of 21,340 as a float, double or decimal. 
        SI_Format will also adjust the value of float, double or decimal such that 34,560 may be written as 34.56kB 
        where "B" was passed as the unit to use.
        Some physical constants are provided for C# use.    </Description>
    <Copyright>Copyright (C) 2018-2023 Information Register, 2024 Information Register Limited</Copyright>
    <Deterministic>true</Deterministic>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <RepositoryUrl>https://github.com/InformationRegisterGH/SI_Format</RepositoryUrl>
    <RepositoryType>github</RepositoryType>
    <Version>1.1.4</Version>
    <FileVersion>1.1.0.0</FileVersion>
    <SignAssembly>False</SignAssembly>
    <DelaySign>True</DelaySign>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	<PackageReleaseNotes>Packaged for .Net6, .Net7 or .Net 8.
The SI_Format package has been reduced in size.
This version uses just two functions Parse and Format.
InfoReg.SI_Format.Parse&lt;double&gt;("5nF", out num);
string ans = InfoReg.SI_Format.Format&lt;decimal&gt;("12.345678912345678", "G21", "grams");
Older functions like ParseDouble will work but are marked obsolete. In the next
release these will produce an error and necessitate migration. Migration is optional in this
release 1.1.4.
	</PackageReleaseNotes>
    <DocumentationFile>C:\Users\Conor\source\repos\SI_Format\SI_Format\SI_Format.xml</DocumentationFile>
    <IncludeSymbols>True</IncludeSymbols>
    <BaseOutputPath>bin\</BaseOutputPath>
    <Title>SI_Format</Title>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>C:\Users\Conor\source\repos\SI_Format\SI_Format\SI_Format.xml</DocumentationFile>
	<PackageReadmeFile>readme.md</PackageReadmeFile>	 
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>true</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>true</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    <PrimaryVersionType>AssemblyFileVersionAttribute</PrimaryVersionType>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="license.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
	<None Include="README.md" Pack="true" PackagePath="\">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
  </ItemGroup>

</Project>
